package csAZelcs;
import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName="appointments")
public class AppointmentModel {
	
	public AppointmentModel() {
		
	}

	public String id;
	public String description;
	public long apDateTime;
	public long duration;
	public String username;
	
	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBAttribute(attributeName="description")
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	
	@DynamoDBAttribute(attributeName="apDateTime")
	public long getDate() {
		return apDateTime;
	}
	public void setDate(long apDateTime) {
		this.apDateTime = apDateTime;
	}
	
	@DynamoDBAttribute(attributeName="duration")
	public long getDuration() {
		return duration;
	}
	public void setDuration(long duration) {
		this.duration = duration;
	}
	
	@DynamoDBIndexHashKey(globalSecondaryIndexName="username")
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}

}
